server:
  error:
    include-message: always

# MySql configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/media_tracker
    username: root
    password: root
  jpa:
    show-sql: true # It shows the sql queries run by JPA into the log
    hibernate:
      ddl-auto: update # It indicates that do not create or drop table everytime this application runs but just update the table
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

